name = "habit"
compatibility_date = "2026-04-09"
main = "worker.js"

# ローカル開発: npx wrangler dev
# 本番デプロイ: npx wrangler deploy

[assets]
directory = "."

[[kv_namespaces]]
binding = "HABIT_DATA"
id = "82dddfc9877941e7886a0ac7dbf6a941"
